#pragma once
const char* commands[] = {
        "takeown /A /R /D Y /F C:\\windows\\temp",
        "md c:\\windows\\temp",
        "del c:\\windows\\logs\\cbs\\*.log",
        "del C:\\Windows\\Logs\\MoSetup\\*.log",
        "del C:\\Windows\\Panther\\*.log /s /q",
        "del C:\\Windows\\inf\\*.log /s /q",
        "del C:\\Windows\\logs\\*.log /s /q",
        "del C:\\Windows\\SoftwareDistribution\\*.log /s /q",
        "del C:\\Windows\\Microsoft.NET\\*.log /s /q",
        "del C:\\Users\\%USERNAME%\\AppData\\Local\\Microsoft\\Windows\\WebCache\\*.log /s /q",
        "del C:\\Users\\%USERNAME%\\AppData\\Local\\Microsoft\\Windows\\SettingSync\\*.log /s /q",
        "del C:\\Users\\%USERNAME%\\AppData\\Local\\Microsoft\\Windows\\Explorer\\ThumbCacheToDelete\\*.tmp /s /q",
        "del C:\\Users\\%USERNAME%\\AppData\\Local\\Microsoft\\\"Terminal Server Client\"\\Cache\\*.bin /s /q",
        "rmdir /q /s C:\\Users\\%USERNAME%\\AppData\\Local\\Microsoft\\Windows\\INetCache\\",
        "rmdir /q /s C:\\Users\\%USERNAME%\\AppData\\Local\\FiveM.app\\data\\cache\\",
        "rmdir /q /s C:\\Users\\%USERNAME%\\AppData\\Local\\DigitalEntitlements\\",
        "del C:\\Users\\%USERNAME%\\AppData\\Local\\DigitalEntitlements",
        "del C:\\Users\\%USERNAME%\\AppData\\Local\\FiveM.app\\data\\cache\\",
        "rmdir /s /q C:\\Users\\%USERNAME%\\AppData\\Local\\FiveM.app\\logs",
        "rmdir /s /q C:\\Users\\%USERNAME%\\AppData\\Local\\FiveM.app\\crashes",
        "powershell -Command \"& {Get-AppxPackage -AllUsers xbox | Remove-AppxPackage}\" >NUL 2>NUL",
        "sc stop XblAuthManager >NUL 2>NUL",
        "sc stop XblGameSave >NUL 2>NUL",
        "sc stop XboxNetApiSvc >NUL 2>NUL",
        "sc stop XboxGipSvc >NUL 2>NUL",
        "sc delete XblAuthManager >NUL 2>NUL",
        "sc delete XblGameSave >NUL 2>NUL",
        "sc delete XboxNetApiSvc >NUL 2>NUL",
        "sc delete XboxGipSvc >NUL 2>NUL",
        "reg delete \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\xbgm\" /f >NUL 2>NUL",
        "reg delete \"HKEY_LOCAL_MACHINE\\SOFTWARE\\INextUUID\" /f",
        "reg delete \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\" /f >NUL 2>NUL",
        "reg delete \"HKEY_CURRENT_USER\\SOFTWARE\\CitizenFX\" /f",
        "reg delete \"HKEY_CURRENT_USER\\SOFTWARE\\Valve\" /f",
        "reg delete \"HKEY_CURRENT_USER\\SOFTWARE\\nk\" /f",
        "reg delete \"HKEY_CURRENT_USER\\SOFTWARE\\FiveM\" /f",
        "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Rockstar Games\\InstallGUID\" /f /v gta5 /t REG_SZ /d {d2237524-fe75-125b-bbcc-b4457fe7d321}",
        "schtasks /Change /TN \"Microsoft\\XblGameSave\\XblGameSaveTask\" /disable >NUL 2>NUL",
        "schtasks /Change /TN \"Microsoft\\XblGameSave\\XblGameSaveTaskLogon\" /disable >NUL 2>NUL",
        "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR\" /v AllowGameDVR /t REG_DWORD /d 0 /f >NUL 2>NUL",
         "RENAME %userprofile%\\AppData\\Roaming\\discord\\0.0.309\\modules\\STARCHARMS_SPOOFER discord_rpc",
         "taskkill /f /im Discord.exe /t",
         "taskkill /f /im DiscordCanary.exe /t",
         "taskkill /f /im Steam.exe /t",
         "set hostspath=%windir%\\System32\\drivers\\etc\\hosts",
         "echo 127.0.0.1 xboxlive.com >> %hostspath%",
         "echo 127.0.0.1 user.auth.xboxlive.com >> %hostspath%",
         "echo 127.0.0.1 presence-heartbeat.xboxlive.com >> %hostspath%",
         "REG DELETE HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\MSLicensing\\HardwareID /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\MSLicensing\\Store /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\WinRAR\\ArcHistory /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\bam\\State\\UserSettings\\S-1-5-21-1282084573-1681065996-3115981261-1001 /va /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\ShowJumpView /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\WinRAR\\ArcHistory /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppSwitched /f",
    "REG DELETE HKEY_CLASSES_ROOT\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\ShowJumpView /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\bam\\State\\UserSettings\\S-1-5-21-332004695-2829936588-140372829-1002 /f",
    "REG DELETE HKEY_CLASSES_ROOT\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Compatibility Assistant\\Store /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppSwitched /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\bam\\State\\UserSettings\\S-1-5-21-1282084573-1681065996-3115981261-1001 /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppSwitched /f",
    "deltree /y c:\\windows\\tempor~1",
    "deltree /y c:\\windows\\temp",
    "deltree /y c:\\windows\\tmp",
    "deltree /y c:\\windows\\ff*.tmp",
    "deltree /y c:\\windows\\history",
    "deltree /y c:\\windows\\cookies",
    "deltree /y c:\\windows\\recent",
    "deltree /y c:\\windows\\spool\\printers",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cfx_curl_x86_64.dll",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\Browser\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\db\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\dunno\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\priv\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\servers\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\subprocess\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\unconfirmed\"",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\steam_api64.dll",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\authbrowser\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\crashometry\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\launcher_skip\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\launcher_skip_mtl2\"",
    "rmdir /s /q \"%LocalAppData%\\DigitalEntitlements\"",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\profiles.dll",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_chrome.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_372.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_1604.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_1868.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_2060.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_2189.bin",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\mods\\*.*\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\logs\\*.*\"",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenGame.dll",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cfx_curl_x86_64.dll\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\steam.dll\"",
    "rmdir /s /q %userprofile%\\AppData\\Roaming\\CitizenFX",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\asi-five.dll\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\CitizenFX.ini\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\caches.XML\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\adhesive.dll\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\discord.dll\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\crashes\\*.*\"",
    "RENAME %userprofile%\\AppData\\Roaming\\discord\\0.0.309\\modules\\discord_rpc STARCHARMS_SPOOFER",
    "taskkill /f /im Steam.exe /t",
    "rmdir /s /q \"%LocalAppData%\\DigitalEntitlements\"",
    "taskkill /f /im Steam.exe /t",
    "rmdir /s /q %userprofile%\\AppData\\Roaming\\CitizenFX",
    "taskkill /f /im Steam.exe /t",
    "set hostspath=%windir%\\System32\\drivers\\etc\\hosts",
    "echo 127.0.0.1 xboxlive.com >> %hostspath%",
    "echo 127.0.0.1 user.auth.xboxlive.com >> %hostspath%",
    "echo 127.0.0.1 presence-heartbeat.xboxlive.com >> %hostspath%",
    "REG DELETE HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\MSLicensing\\HardwareID /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\MSLicensing\\Store /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\WinRAR\\ArcHistory /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\bam\\State\\UserSettings\\S-1-5-21-1282084573-1681065996-3115981261-1001 /va /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\ShowJumpView /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Compatibility Assistant\\Store /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppSwitched /f",
    "REG DELETE HKEY_CLASSES_ROOT\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\bam\\State\\UserSettings\\S-1-5-21-332004695-2829936588-140372829-1002 /f",
    "REG DELETE HKEY_CLASSES_ROOT\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Compatibility Assistant\\Store /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppSwitched /f",
    "REG DELETE HKEY_LOCAL_MACHINE\\SYSTEM\\ControlSet001\\Services\\bam\\State\\UserSettings\\S-1-5-21-1282084573-1681065996-3115981261-1001 /f",
    "REG DELETE HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FeatureUsage\\AppSwitched /f",
    "deltree /y c:\\windows\\tempor~1",
    "deltree /y c:\\windows\\temp",
    "deltree /y c:\\windows\\tmp",
    "deltree /y c:\\windows\\ff*.tmp",
    "deltree /y c:\\windows\\history",
    "deltree /y c:\\windows\\cookies",
    "deltree /y c:\\windows\\recent",
    "deltree /y c:\\windows\\spool\\printers",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_chrome.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_372.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_1604.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_1868.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_2060.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX_SubProcess_game_2189.bin",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\botan.dll",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\asi-five.dll",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\steam.dll",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\steam_api64.dll",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenGame.dll",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\profiles.dll",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cfx_curl_x86_64.dll\"",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\CitizenFX.ini",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\caches.XML",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\adhesive.dll",
    "taskkill /f /im Steam.exe /t",
    "del /s /q /f %LocalAppData%\\FiveM\\FiveM.app\\discord.dll",
    "RENAME %userprofile%\\AppData\\Roaming\\discord\\0.0.309\\modules\\discord_rpc STARCHARMS_SPOOFER",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\Browser\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\db\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\dunno\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\priv\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\servers\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\subprocess\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\unconfirmed\"",
    "rmdir /s /q \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\authbrowser\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\crashometry\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\launcher_skip\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\cache\\launcher_skip_mtl2\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\crashes\\*.*\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\logs\\*.*\"",
    "del /s /q /f \"%LocalAppData%\\FiveM\\FiveM.app\\mods\\*.*\"",
    "rmdir /q /s \"C:\\Program Files\\Rockstar Games\\Launcher\\ThirdParty\""
};
void FivemClean() {
    killer();

    for (const auto& command : commands) {
        if (system(command) != 0) {
        }
    }
    MessageBoxA(0, skCrypt("Clean Done").decrypt(), skCrypt("Shadow").decrypt(), 0);
}